const express = require("express");
const app = express();
require("dotenv").config();
const port = process.env.PORT;
const cors = require("cors");
const router = require("./router/mainRouter");
const mongoose = require("mongoose");
mongoose.connect(process.env.DB_KEY);
app.use(cors());
app.use(express.json());
app.use("/", router);
app.listen(port);